-- INSERTAR DATOS EN TABLAS
-- Usuarios
INSERT INTO USUARIO (NOMBREUSUARIO,CONTRASENA,ROL) VALUES ("ADMIN","1234","admin");
INSERT INTO USUARIO (NOMBREUSUARIO,CONTRASENA,ROL) VALUES ("SUPERVISOR","1234","supervisor");
INSERT INTO USUARIO (NOMBREUSUARIO,CONTRASENA,ROL) VALUES ("OPERARIO","1234","operario");

-- Orden de Trabajo
INSERT INTO ORDENTRABAJO(NUMEROORDEN,DESCRIPCION,FECHAINICIO,FECHAFIN,USUARIO) VALUES(100,"FABRICACION TK","20240629",NULL,"ADMIN");

-- Tareas 
INSERT INTO TAREA(ORDENTRABAJOID,NUMEROORDENTAREA,DESCRIPCION,FECHAINICIO,COMPLETADA,USUARIORESPONSABLE)VALUES(8,10,"LIMPIEZA DE MATRIZ", "20240629",0,"ADMIN");
INSERT INTO TAREA(ORDENTRABAJOID,NUMEROORDENTAREA,DESCRIPCION,FECHAINICIO,COMPLETADA,USUARIORESPONSABLE)VALUES(8,20,"ENCERADO", "20240629",0,"ADMIN");
INSERT INTO TAREA(ORDENTRABAJOID,NUMEROORDENTAREA,DESCRIPCION,FECHAINICIO,COMPLETADA,USUARIORESPONSABLE)VALUES(8,30,"BARRERA QUÍMICA", "20240629",0,"ADMIN");
INSERT INTO TAREA(ORDENTRABAJOID,NUMEROORDENTAREA,DESCRIPCION,FECHAINICIO,COMPLETADA,USUARIORESPONSABLE)VALUES(8,40,"REFUERZO MECÁNICO", "20240629",0,"ADMIN");
INSERT INTO TAREA(ORDENTRABAJOID,NUMEROORDENTAREA,DESCRIPCION,FECHAINICIO,COMPLETADA,USUARIORESPONSABLE)VALUES(8,50,"COLOCACION DE CÁNCAMOS", "20240629",0,"ADMIN");
INSERT INTO TAREA(ORDENTRABAJOID,NUMEROORDENTAREA,DESCRIPCION,FECHAINICIO,COMPLETADA,USUARIORESPONSABLE)VALUES(8,60,"LIMPIEZA INTERIOR", "20240629",0,"ADMIN");
INSERT INTO TAREA(ORDENTRABAJOID,NUMEROORDENTAREA,DESCRIPCION,FECHAINICIO,COMPLETADA,USUARIORESPONSABLE)VALUES(8,70,"AMOLADO PARA PINTAR EXTERIOR", "20240629",0,"ADMIN");
INSERT INTO TAREA(ORDENTRABAJOID,NUMEROORDENTAREA,DESCRIPCION,FECHAINICIO,COMPLETADA,USUARIORESPONSABLE)VALUES(8,80,"PINTURA CON GEL COAT", "20240629",0,"ADMIN");

-- Consulta de datos insertados
SELECT O.NUMEROORDEN, O.DESCRIPCION, O.FECHAINICIO AS 'FECHA_OT', T.NUMEROORDENTAREA,T.DESCRIPCION,T.FECHAINICIO, T.USUARIORESPONSABLE
FROM ORDENTRABAJO O INNER JOIN TAREA T ON O.ID=T.ORDENTRABAJOID WHERE O.ID=8